method: random
metric:
  goal: minimize
  name: Validation Loss
parameters:
  batch_size:
    distribution: categorical
    values:
    - 64
    - 128
    - 256
  dataset_name:
    distribution: categorical
    values:
    - BRAIX
  earlystop_patience:
    distribution: constant
    value: 15
  epochs:
    distribution: categorical
    values:
    - 100
    - 150
    - 200
  first_out_channels:
    distribution: categorical
    values:
    - 4
    - 8
    - 16
  image_channels:
    distribution: constant
    value: 1
  imageinfo_clinical_path:
    distribution: categorical
    values:
    - ./data/Hui_BRAIX_subset_info.xlsx
  latent_dim:
    distribution: categorical
    values:
    - 128
    - 256
    - 384
  learning_rate:
    distribution: uniform
    max: 0.01
    min: 0
  model:
    distribution: categorical
    values:
    - VanillaCVAE
  num_workers:
    distribution: constant
    value: 6
  optimizer:
    distribution: categorical
    values:
    - adam
  reduceLR_patience:
    distribution: constant
    value: 5
  resize_height:
    distribution: categorical
    values:
    - 128
    - 256
    - 512
  resize_width:
    distribution: categorical
    values:
    - 128
    - 256
    - 512
  save_dir:
    distribution: categorical
    values:
    - ./output/
  seed:
    distribution: constant
    value: 42
  train_set_ratio:
    distribution: constant
    value: 0.8
  tune_hyperparameter:
    distribution: categorical
    values:
    - true
  valid_set_ratio:
    distribution: constant
    value: 0.1
